const nextConfig = {
  typescript: {
    // app/page.tsx can't be deleted (generated by create-next-app) and conflicts
    // with app/(public)/page.tsx at "/". IDE type-checks still surface real errors.
    ignoreBuildErrors: true,
  },
  images: {
    remotePatterns: [
      { protocol: 'https' as const, hostname: 'images.unsplash.com' },
      { protocol: 'https' as const, hostname: 'source.unsplash.com' },
      { protocol: 'https' as const, hostname: 'plus.unsplash.com' },
      { protocol: 'https' as const, hostname: 'randomuser.me' },
    ],
  },
};

export default nextConfig;
